### ISSUE TITLE
Evaluating your pretrained model

### ISSUE THREAD

**Issue by oconnor127** [wvangansbeke/Sparse-Depth-Completion#40] opened 2020-11-20 09:37 UTC
Hey,

I want to use your pretrained model (KITTI) to output some depth-maps. Therefore I created a dataset folder as you said
Running 

$source Test/test.sh /home/username/Desktop/bryan/Sparse-Depth-Completion/mod/model_best_epoch.pth.tar 5 /home/username/Desktop/bryan/data/ /home/username/Desktop/bryan/groundtruth_depth/

Gives me the error:
Save path is: /home/username/Desktop/bryan/Sparse-Depth-Completion/mod/model_best_epoch.pth.tar
Data path is: /home/username/Desktop/bryan/data/
/home/username/Desktop/bryan/Sparse-Depth-Completion
Traceback (most recent call last):
  File "Test/test.py", line 164, in <module>
    main()
  File "Test/test.py", line 54, in main
    best_file_name = glob.glob(os.path.join(args.save_path, 'model_best*'))[0]
IndexError: list index out of range
Test/devkit/cpp/evaluate_depth /home/username/Desktop/bryan/groundtruth_depth/ Saved//home/username/Desktop/bryan/Sparse-Depth-Completion/mod/model_best_epoch.pth.tar/results 
Starting depth evaluation..
Number of groundtruth (5) and prediction files (-1) mismatch!
Segmentation fault (core dumped)

the structure of the "data"folder is as you mentioned it: Parent folder "data", subfolder "Depth", "depth_selection", "RGB" where "Depth" and "RGB" has the subfolder validation where the images directly (without any subfolders) are.

**Comment by wvangansbeke** [comment] 2020-11-20 09:54
Hi @oconnor127,

`save_path` should be the directory where the best model is located and not the model itself. 
Or you can set the `best_file_name` variable directly.

Hope this helps.

**Comment by oconnor127** [comment] 2020-11-20 10:14
Thanks for your quick response. I get the same error when typing the path of the model directory "mod"

source Test/test.sh /home/username/Desktop/bryan/Sparse-Depth-Completion/mod/ 5 /home/username/Desktop/bryan/data/ /home/username/Desktop/bryan/groundtruth_depth/

**Comment by wvangansbeke** [comment] 2020-11-20 10:33
Can you try to set the model path manually [here](https://github.com/wvangansbeke/Sparse-Depth-Completion/blob/master/Test/test.py#L54) because it clearly fails at that line. Or set a print statement for `best_file_name`. This will tell you if the path to the model is at least correct.

**Comment by oconnor127** [comment] 2020-11-20 11:46
Ok thanks, this works, but for some reason I the output-depthmap is not correct. It works with the following command:

$source Test/test.sh /home/username/Desktop/bryan/Sparse-Depth-Completion/mod/ 5 /home/username/Desktop/bryan/data/data_depth_selection/

were data_depth_selection is the raw-kitti-dataset containing depth_selection/val_selection_cropped/..
I've downloaded your model "model_best_epoch.pth.tar"

Is it correct to only give the path to the raw-dataset? The created depth map does have the correct names (sequences) and no error occurs. Is there a way to process (obtain dense depth maps) the validation_dataset from kitti in their original structure?

**Comment by wvangansbeke** [comment] 2020-11-20 12:05
Normally you should get the exact numbers from the paper. What RMSE do you get? 

Yes the path seems correct. Just verify the amount of files to make sure.

**Comment by oconnor127** [comment] 2020-11-20 13:13
I just let your approach to create a small amount of depthmaps and abort after some iterations. Thus, I didnt had a look at RMSE or anything. The depthmap (screenshot) the first file (I think) is attached. The contours are visible, but there is still some main issue. (Dont worry about the artifact on the right side, thats just caused by the process of making the depthmap brighter to see it better)
![Bildschirmfoto vom 2020-11-20 12-40-43](https://user-images.githubusercontent.com/54242789/99803906-7c64a400-2b3a-11eb-80c6-06f2ca25d454.png)

**Comment by wvangansbeke** [comment] 2020-11-20 13:44
Yes it should look better. Can you set a breakpoint at the start of the loop in `test/test.py` and check the filenames. Make sure that the RGB and LiDAR filenames match. Maybe let it finish to check what RMSE you get. If you don't get 802mm rmse, something is still wrong.

**Comment by oconnor127** [comment] 2020-11-24 09:40
Hm, unfortunately the paths are correct. For the first iteration it gives:

/home/username/Desktop/bryan/data/data_depth_selection/depth_selection/val_selection_cropped/velodyne_raw/2011_09_26_drive_0002_sync_velodyne_raw_0000000005_image_02.png

/home/username/Desktop/bryan/data/data_depth_selection/depth_selection/val_selection_cropped/image/2011_09_26_drive_0002_sync_image_0000000005_image_02.png

Do you have any other idea?

**Comment by wvangansbeke** [comment] 2020-11-24 10:36
Hi @oconnor127,

The paths look indeed correct.
I just ran `test.sh` in this code repository and I get the following
[test_log.txt](https://github.com/wvangansbeke/Sparse-Depth-Completion/files/5589139/test_log.txt). At the end, you can see that you should get 802 mm RMSE. 

Did you already run it completely? It's not easy for me to say how a specific image should look like.

**Comment by oconnor127** [comment] 2020-11-24 11:51
After trying to run it till the end, I get the following error:
Lowest RMSE for selection validation set was 0.7908 in epoch 59
Initializing dataset kitti
0
0
0
0
0
0
1000
1000
===> Start testing
1000it [02:55,  5.69it/s]
average_time:  0.035244497482227514
num imgs:  1000
Test/devkit/cpp/evaluate_depth /home/username/Desktop/bryan/data/data_depth_selection/depth_selection/val_selection_cropped/groundtruth_depth Saved//home/username/Desktop/bryan/Sparse-Depth-Completion/mod//results 
Starting depth evaluation..
Number of groundtruth (1000) and prediction files (-1) mismatch!
Segmentation fault (core dumped)

I've used the following command: source Test/test.sh /home/username/Desktop/bryan/Sparse-Depth-Completion/mod/ 1000 /home/username/Desktop/bryan/data/data_depth_selection/ /home/username/Desktop/bryan/data/data_depth_selection/depth_selection/val_selection_cropped/groundtruth_depth

I guess the errors is caused also by the 0,0,0,0,0,0,1000,1000 on the top. I think this might be a structure problem am I right? I just downloaded the dataset and gave the validation_path as argument...Is that correct? Do I need the entire dataset to only evaluate the data_depth_selection (val_selection_cropped)? I just want to evaluate the 1000 validation images.

**Comment by wvangansbeke** [comment] 2020-11-24 13:01
Hi @oconnor127,

Please check your save directory. Clearly, `Saved//home/username/Desktop/bryan/Sparse-Depth-Completion/mod//results` is incorrect if you pass `/home/username/Desktop/bryan/Sparse-Depth-Completion/mod` to `test.sh`. Remove  `Saved` at the bottom of the file `test.sh`. The error is quite obvious. It tells you it can not find the 1000 predictions. To solve this issue, the path should be `/home/username/Desktop/bryan/Sparse-Depth-Completion/mod//result`.

Please read the README. There is mentioned how you should use the pretrained model. However, changing the path should fix your issue. 

Hope this helps.
Cheers.

**Comment by oconnor127** [comment] 2020-11-24 13:13
But still this is just an evaluation issue. The main issue regarding the incorrect depth map has nothing to do with that. I got it to run and obtain the mae of 10.3843.

**Comment by wvangansbeke** [comment] 2020-11-24 13:25
It is hard for me to say what else is incorrect. You should follow the README. Make a directory called `Saved` and put the directory with the model in there. Then you should only change 2 paths in `Test/test.sh`. (Please don't change other parameters like `num_samples`, it should be the default value). I downloaded the repository and the model this morning and I got the expected results (other people also confirmed the numbers).

**Comment by oconnor127** [comment] 2020-11-24 16:02
Hmm weird. I tried it again from scratch and still the same mae (without any error msg).. And the model to download is : model_best_epoch.pth.tar correct?
Nevertheless, thank you for your help.

**Comment by wvangansbeke** [comment] 2020-11-24 21:48
Hi @oconnor127,

Yes indeed. Are you sure you calculate the mae correctly? 
Can you try downloading the dataset again. Maybe the dataset got corrupted. Also not sure if it has something to do with the fact that you're using windows.

To help you further, I will give the exact code and commands I run. You can download the code, model and results as a single zip-file from [here](https://drive.google.com/file/d/1MxtFLUcmtQ7jOTCOFqzxesFsJDt-2Jpk/view?usp=sharing). First unzip the files. Then change the path to the dataset in `Test/test.sh`. Finally, you only need to run `sh Test/test.sh best`. You can also find my predictions in the directory `Saved/best/results/`.

Hope this helps.

**Comment by wvangansbeke** [comment] 2020-12-08 20:03
Hi @oconnor127,

Do you get the expected results or are there still some problems?

**Comment by wvangansbeke** [comment] 2021-01-03 18:20
If something is still unclear, let me know. Closing this for now.

**Closed as completed by wvangansbeke** 2021-01-03 18:20 UTC
